### PR TITLE
Use automated integration tests

### PR DESCRIPTION
**Pull request by kbalk**
Uses tardigrade-ci's ability to run automated integration tests against a mock AWS stack.

### CODE REVIEW

**Comment by lorengordon** [comment]
Closing and re-opening to trigger travis-ci...

**Comment by kbalk** [comment]
Kick-starting Travis again.

**Comment by kbalk** [comment]
Another kick-start?

**Comment by lorengordon** [comment]
This one does seem stuck pretty hard. Very odd. Might try amending the last commit, or even opening a new pr on the same branch.

**Comment by kbalk** [comment]
I'll try a new PR.

**Pull request closed without merging**
